# Generated by Django 5.2.1 on 2025-06-04 15:48

import django.db.models.deletion
import shorts_app.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadedVideo',
            fields=[
                ('video_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('file_path', models.FileField(storage=shorts_app.models.YoutubeVideoStorage(), upload_to='')),
                ('thumbnail_path', models.FileField(blank=True, null=True, storage=shorts_app.models.YoutubeVideoStorage(), upload_to='')),
                ('suggestions', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedShort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(default=list)),
                ('short_path', models.FileField(storage=shorts_app.models.ShortsStorage(), upload_to='')),
                ('thumbnail_path', models.FileField(storage=shorts_app.models.ShortsStorage(), upload_to='')),
                ('start_time', models.CharField(max_length=12)),
                ('end_time', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shorts', to='shorts_app.downloadedvideo')),
            ],
        ),
    ]
