# Generated by Django 5.2.1 on 2025-06-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedshort',
            name='thumbnail_path',
            field=models.FileField(blank=True, null=True),
        ),
    ]
