# Generated by Django 5.2.1 on 2025-06-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedshort',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='generatedshort',
            name='start_time',
        ),
        migrations.AddField(
            model_name='generatedshort',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generatedshort',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='generatedshort',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='downloadedvideo',
            name='thumbnail_path',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='generatedshort',
            name='thumbnail_path',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
