# Generated by Django 5.2.1 on 2025-05-25 11:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts_app', '0002_downloadedvideo_suggestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadedvideo',
            name='id',
        ),
        migrations.AlterField(
            model_name='downloadedvideo',
            name='file_path',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='downloadedvideo',
            name='thumbnail_path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='downloadedvideo',
            name='video_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='GeneratedShort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(default=list)),
                ('short_path', models.CharField(max_length=512)),
                ('thumbnail_path', models.CharField(max_length=512)),
                ('start_time', models.CharField(max_length=12)),
                ('end_time', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shorts', to='shorts_app.downloadedvideo')),
            ],
        ),
    ]
