# Generated by Django 5.2.1 on 2025-05-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts_app', '0002_youtubeupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadedvideo',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
