# Generated by Django 5.2.1 on 2025-05-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts_app', '0003_downloadedvideo_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadedvideo',
            name='suggestions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
