# Generated by Django 5.2.1 on 2025-06-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts_app', '0003_remove_downloadedvideo_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedshort',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generatedshort',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='generatedshort',
            name='end_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='generatedshort',
            name='start_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='generatedshort',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generatedshort',
            name='thumbnail_path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
