# Generated by Django 5.2.1 on 2025-06-08 20:30

import django.db.models.deletion
import uuid
import videocraft_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCraftProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_file', models.ImageField(storage=videocraft_app.models.VideoCraftImageStorage(), upload_to='')),
                ('order', models.IntegerField(default=0)),
                ('text_overlay', models.TextField(blank=True, null=True)),
                ('duration', models.FloatField(default=3.0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='videocraft_app.videocraftproject')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_file', models.FileField(storage=videocraft_app.models.VideoCraftVideoStorage(), upload_to='')),
                ('audio_file_url', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generated_video', to='videocraft_app.videocraftproject')),
            ],
        ),
    ]
