# Generated by Django 5.2.4 on 2025-07-16 05:38

import videocraft_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videocraft_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedvideo',
            name='video_file',
            field=models.FileField(blank=True, null=True, storage=videocraft_app.models.VideoCraftVideoStorage(), upload_to=''),
        ),
    ]
